import { readFile, writeFile } from 'node:fs/promises';
import { isBuiltin } from 'node:module';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { build } from 'esbuild';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '../..');
const OUTPUT = 'moldea/scripts/manifest-scope.cjs';
const LICENSES = 'moldea/scripts/manifest-scope.license.txt';
// release artifact headroom; this is not a repository or model-output limit
const MAXIMUM_BUNDLE_BYTES = 1_048_576;

/** Builds a reproducible matcher from locked packages, without writing or executing the bundle. */
export const buildPortableMatcher = async () => {
  const result = await build({
    absWorkingDir: ROOT,
    entryPoints: ['tooling/relevance-gate/matcher.mjs'],
    bundle: true,
    format: 'cjs',
    platform: 'node',
    target: 'node22.11',
    write: false,
    metafile: true,
    minifySyntax: true,
    minifyWhitespace: true,
    legalComments: 'inline',
    alias: { process: 'node:process', buffer: 'node:buffer' },
    banner: { js: '// Generated by npm run matcher:generate. See manifest-scope.license.txt.' },
  });
  const source = result.outputFiles[0].text;
  if (Buffer.byteLength(source) > MAXIMUM_BUNDLE_BYTES) {
    throw new Error('The portable matcher exceeded its reviewed artifact size limit.');
  }
  const imports = Object.values(result.metafile.outputs).flatMap((output) => output.imports);
  if (imports.some((entry) => !entry.path.startsWith('node:') || !isBuiltin(entry.path))) {
    throw new Error('The portable matcher retains a non-builtin runtime dependency.');
  }

  const lock = JSON.parse(await readFile(join(ROOT, 'package-lock.json'), 'utf8'));
  const packageRoots = new Set();
  for (const input of Object.keys(result.metafile.inputs)) {
    const marker = input.lastIndexOf('node_modules/');
    if (marker === -1) {
      if (input !== 'tooling/relevance-gate/matcher.mjs') {
        throw new Error(`Unexpected matcher build input: ${input}`);
      }
      continue;
    }
    const segments = input.slice(marker + 'node_modules/'.length).split('/');
    packageRoots.add(
      input.slice(0, marker) +
        'node_modules/' +
        segments.slice(0, segments[0].startsWith('@') ? 2 : 1).join('/'),
    );
  }
  const notices = [];
  for (const packageRoot of [...packageRoots].sort()) {
    const manifest = JSON.parse(await readFile(join(ROOT, packageRoot, 'package.json'), 'utf8'));
    if (lock.packages[packageRoot]?.version !== manifest.version) {
      throw new Error(`Matcher dependency does not match the lockfile: ${manifest.name}`);
    }
    const license = await readFile(join(ROOT, packageRoot, 'LICENSE'), 'utf8');
    notices.push(`${manifest.name}@${manifest.version}\n\n${license.trim()}\n`);
  }
  return { source, licenses: notices.join('\n'), imports, packageCount: packageRoots.size };
};

/** Generates the portable artifact or fails when committed output differs from locked inputs. */
export const generatePortableMatcher = async ({ check = false } = {}) => {
  const { source, licenses } = await buildPortableMatcher();
  for (const [path, content] of [
    [OUTPUT, source],
    [LICENSES, licenses],
  ]) {
    if (check) {
      if ((await readFile(join(ROOT, path), 'utf8')) !== content) {
        throw new Error(`Generated matcher artifact is stale: ${path}`);
      }
    } else {
      await writeFile(join(ROOT, path), content);
    }
  }
};

if (process.argv[1] && pathToFileURL(resolve(process.argv[1])).href === import.meta.url) {
  const args = process.argv.slice(2);
  if (args.length > 1 || (args.length === 1 && args[0] !== '--check')) {
    throw new Error('Usage: generate-matcher.mjs [--check]');
  }
  await generatePortableMatcher({ check: args[0] === '--check' });
  process.stdout.write(
    args.length ? 'Portable matcher is current.\n' : 'Generated portable matcher.\n',
  );
}
